export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';
export const CHANGE_PLAY_LIST = 'player/CHANGE_PLAY_LIST';
export const CHANGE_CURRENT_SONG_INDEX = 'player/CHANGE_CURRENT_SONG_INDEX';

export const CHANGE_SEQUENCE = 'player/CHANGE_SEQUENCE';
export const CHANGE_LYRICS_LIST = 'player/CHANGE_LYRICS_LIST';
export const CHANGE_CURRENT_LYRIC_INDEX = 'player/CHANGE_CURRENT_LYRIC_INDEX';

export const CHANGE_CURRENT_LYRIC_COUNT='player/CHANGE_CURRENT_LYRIC_COUNT'

export const CHANGE_PLAY_LIST_COUNT = 'player/CHANGE_PLAY_LIST_COUNT'

// export const CHANGE_CURRENT_TOTAL = 'player/CHANGE_CURRENT_TOTAL';
// export const CHANGE_HOT_COMMENTS='player/CHANGE_HOT_COMMENTS'
