/**--------------- */
export const CHANGE_SHOW_CURRENT_SONG_ID = 'song/CHANGE_SHOW_CURRENT_SONG_ID';
export const CHANGE_SHOW_CURRENT_SONG_DETAIL = 'song/CHANGE_SHOW_CURRENT_SONG_DETAIL';
export const CHANGE_SHOW_CURRENT_SONG_COMMENT_TOTAL = 'song/CHANGE_SHOW_CURRENT_SONG_COMMENT_TOTAL';
export const CHANGE_SHOW_CURRENT_SONG_HOT_COMMENT='song/CHANGE_SHOW_CURRENT_SONG_HOT_COMMENT';
export const CHANGE_SHOW_CURRENT_SONG_COMMENT = 'song/CHANGE_SHOW_CURRENT_SONG_COMMENT'
export const CHANGE_SHOW_CURRENT_SONG_LYRIC_LIST = 'song/CHANGE_SHOW_CURRENT_SONG_LYRIC_LIST'