// 常量Type
export const CHANGE_SONG_LIST_ID = 'songList/CHANGE_SONG_LIST_ID'
export const CHANGE_SONG_LIST_INFO = 'songList/CHANGE_SONG_LIST_INFO'
export const CHANGE_SONG_LIST_PLAY_LIST = 'songList/CHANGE_SONG_LIST_PLAY_LIST'

export const CHANGE_SONG_LIST_RECOMMEND = 'songList/CHANGE_SONG_LIST_RECOMMEND'
export const CHANGE_SONG_LIST_COLLECTOR = 'songList/CHANGE_SONG_LIST_COLLECTOR'