export const CHANGE_ARTIST_CURRENT_INDEX = 'artist/CHANGE_ARTIST_CURRENT_INDEX'
export const CHANGE_ARTIST_CURRENT_ID = 'artist/CHANGE_ARTIST_CURRENT_ID'
export const CHANGE_ARTIST_CURRENT_INFO = 'artist/CHANGE_ARTIST_CURRENT_INFO'
export const CHANGE_ARTIST_LIST_INFO = 'artist/CHANGE_ARTIST_LIST_INFO'