export const CHANGE_ALBUM_ID = 'album/CHANGE_ALBUM_ID'

export const CHANGE_ALBUM_DETAIL = 'album/CHANGE_ALBUM_DETAIL'
export const CHANGE_ALBUM_WORKS = 'album/CHANGE_ALBUM_WORKS'
export const CHANGE_ALBUM_ALBUM = 'album/CHANGE_ALBUM_ALBUM'
export const CHNAGE_ALBUM_DESC = 'album/CHNAGE_ALBUM_DESC'

export const CHANGE_OTHER_ALBUM = 'album/CHANGE_OTHER_ALBUM'