export const CHANGE_TOPLIST_COUNT = 'ranking/CHANGE_TOPLIST_COUNT';

export const CHANGE_CURRENT_INDEX = 'ranking/CHANGE_CURRENT_INDEX';
export const CHANGE_CURRENT_TOPLIST_ID = 'ranking/CHANGE_CURRENT_TOPLIST_ID';

export const CHANGE_CURRENT_TOPLIST_TITLE_INFO= 'ranking/CHANGE_CURRENT_TOPLIST_TITLE_INFO'
export const CHANGE_CURRENT_TOPLIST = 'ranking/CHANGE_CURRENT_TOPLIST'
